# MySQL database settings
database:
  host: localhost
  user: admin
  password: phpmyadmin
  name: eurobusiness
  prefix: ""
  charset: utf8

# Security settings
security:
  hashsalt: "€urobu$ine$$"

# Should we enable logging for errors?
debug: true
